apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-{{.Values.moduleName | lower}}
  namespace: {{.Values.apptag | lower}}
spec:
  ingressClassName: ngrok
  rules:
    - host: {{.Values.ngrokDomain | lower}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-{{.Values.moduleName | lower}}
                port:
                  number: 8080